const WORDS = [
  { id: 1, word: 'accept', pos: '動詞', meaning: '受け入れる、承諾する' },
  { id: 2, word: 'achieve', pos: '動詞', meaning: '達成する、成し遂げる' },
  { id: 3, word: 'add', pos: '動詞', meaning: '加える、追加する' },
  { id: 4, word: 'advertisement', pos: '名詞', meaning: '広告（縮めて ad とも言う）' },
  { id: 5, word: 'advice', pos: '名詞', meaning: '助言、アドバイス' },
  { id: 6, word: 'advise', pos: '動詞', meaning: '忠告する、アドバイスする' },
  { id: 7, word: 'affect', pos: '動詞', meaning: '影響を与える' },
  { id: 8, word: 'afford', pos: '動詞', meaning: '～する余裕がある（主に金銭的・時間的）' },
  { id: 9, word: 'agree', pos: '動詞', meaning: '同意する、意見が一致する' },
  { id: 10, word: 'allow', pos: '動詞', meaning: '許可する、～させる' },
  { id: 11, word: 'amount', pos: '名詞', meaning: '量、金額' },
  { id: 12, word: 'announcement', pos: '名詞', meaning: '発表、アナウンス' },
  { id: 13, word: 'appear', pos: '動詞', meaning: '現れる、～のように見える' },
  { id: 14, word: 'apply', pos: '動詞', meaning: '申し込む、応募する' },
  { id: 15, word: 'appointment', pos: '名詞', meaning: '（面会の）約束、予約' },
  { id: 16, word: 'area', pos: '名詞', meaning: '地域、区域、分野' },
  { id: 17, word: 'arrange', pos: '動詞', meaning: '手配する、配置する' },
  { id: 18, word: 'arrive', pos: '動詞', meaning: '到着する' },
  { id: 19, word: 'article', pos: '名詞', meaning: '記事、品物' },
  { id: 20, word: 'assistant', pos: '名詞', meaning: '助手、アシスタント' },
  { id: 21, word: 'attend', pos: '動詞', meaning: '出席する、参加する' },
  { id: 22, word: 'attention', pos: '名詞', meaning: '注意、注目' },
  { id: 23, word: 'available', pos: '形容詞', meaning: '利用可能な、入手可能な、手があいている' },
  { id: 24, word: 'avoid', pos: '動詞', meaning: '避ける' },
  { id: 25, word: 'base', pos: '動詞', meaning: '～の基礎を置く、拠点にする' },
  { id: 26, word: 'begin', pos: '動詞', meaning: '始まる、始める' },
  { id: 27, word: 'benefit', pos: '名詞', meaning: '利益、恩恵、手当' },
  { id: 28, word: 'board', pos: '名詞', meaning: '取締役会、掲示板 / 動詞：搭乗する' },
  { id: 29, word: 'borrow', pos: '動詞', meaning: '（無料で）借りる' },
  { id: 30, word: 'boss', pos: '名詞', meaning: '上司、ボス' },
  { id: 31, word: 'build', pos: '動詞', meaning: '建てる、築く' },
  { id: 32, word: 'business', pos: '名詞', meaning: '仕事、ビジネス、会社' },
  { id: 33, word: 'busy', pos: '形容詞', meaning: '忙しい、にぎわっている' },
  { id: 34, word: 'buy', pos: '動詞', meaning: '買う' },
  { id: 35, word: 'call', pos: '動詞', meaning: '電話をかける、呼ぶ' },
  { id: 36, word: 'cancel', pos: '動詞', meaning: '取り消す、キャンセルする' },
  { id: 37, word: 'candidate', pos: '名詞', meaning: '候補者' },
  { id: 38, word: 'careful', pos: '形容詞', meaning: '注意深い' },
  { id: 39, word: 'carry', pos: '動詞', meaning: '運ぶ、（商品を）扱う' },
  { id: 40, word: 'case', pos: '名詞', meaning: '場合、事件、箱' },
  { id: 41, word: 'cause', pos: '動詞', meaning: '引き起こす' },
  { id: 42, word: 'celebrate', pos: '動詞', meaning: '祝う' },
  { id: 43, word: 'center', pos: '名詞', meaning: '中心、センター' },
  { id: 44, word: 'certain', pos: '形容詞', meaning: '確実な、ある特定の' },
  { id: 45, word: 'change', pos: '動詞', meaning: '変える、変わる' },
  { id: 46, word: 'charge', pos: '名詞', meaning: '料金、責任' },
  { id: 47, word: 'cheap', pos: '形容詞', meaning: '安い' },
  { id: 48, word: 'check', pos: '動詞', meaning: '確認する、調べる' },
  { id: 49, word: 'choose', pos: '動詞', meaning: '選ぶ' },
  { id: 50, word: 'clear', pos: '形容詞', meaning: '明確な、はっきりした' },
  { id: 51, word: 'close', pos: '動詞', meaning: '閉める' },
  { id: 52, word: 'collect', pos: '動詞', meaning: '集める、回収する' },
  { id: 53, word: 'company', pos: '名詞', meaning: '会社' },
  { id: 54, word: 'compare', pos: '動詞', meaning: '比較する' },
  { id: 55, word: 'complain', pos: '動詞', meaning: '苦情を言う、クレームをつける' },
  { id: 56, word: 'complete', pos: '動詞', meaning: '完了する、記入する' },
  { id: 57, word: 'confirm', pos: '動詞', meaning: '確認する、確定する' },
  { id: 58, word: 'consider', pos: '動詞', meaning: 'よく考える、検討する' },
  { id: 59, word: 'continue', pos: '動詞', meaning: '続ける、続く' },
  { id: 60, word: 'contract', pos: '名詞', meaning: '契約、契約書' },
  { id: 61, word: 'cost', pos: '名詞', meaning: '費用、コスト' },
  { id: 62, word: 'create', pos: '動詞', meaning: '創造する、作り出す' },
  { id: 63, word: 'customer', pos: '名詞', meaning: '顧客、客' },
  { id: 64, word: 'decide', pos: '動詞', meaning: '決める、決定する' },
  { id: 65, word: 'decrease', pos: '動詞', meaning: '減少する、減らす' },
  { id: 66, word: 'delay', pos: '動詞', meaning: '遅らせる、延期する' },
  { id: 67, word: 'deliver', pos: '動詞', meaning: '配達する、（スピーチを）行う' },
  { id: 68, word: 'demand', pos: '名詞', meaning: '需要、要求' },
  { id: 69, word: 'department', pos: '名詞', meaning: '部、課、売り場' },
  { id: 70, word: 'depend', pos: '動詞', meaning: '～次第である、頼る' },
  { id: 71, word: 'describe', pos: '動詞', meaning: '説明する、描写する' },
  { id: 72, word: 'design', pos: '動詞', meaning: '設計する、デザインする' },
  { id: 73, word: 'develop', pos: '動詞', meaning: '開発する、発展させる' },
  { id: 74, word: 'difference', pos: '名詞', meaning: '違い、差' },
  { id: 75, word: 'different', pos: '形容詞', meaning: '異なる、違った' },
  { id: 76, word: 'difficult', pos: '形容詞', meaning: '難しい' },
  { id: 77, word: 'direct', pos: '動詞', meaning: '指示する、向ける' },
  { id: 78, word: 'director', pos: '名詞', meaning: '取締役、ディレクター、映画監督' },
  { id: 79, word: 'discuss', pos: '動詞', meaning: '話し合う、議論する' },
  { id: 80, word: 'display', pos: '動詞', meaning: '展示する、表示する' },
  { id: 81, word: 'divide', pos: '動詞', meaning: '分ける、分割する' },
  { id: 82, word: 'document', pos: '名詞', meaning: '書類、文書' },
  { id: 83, word: 'draw', pos: '動詞', meaning: '（線を）引く、（絵を）描く、（注意を）引く' },
  { id: 84, word: 'due', pos: '形容詞', meaning: '期限が来て、～する予定で' },
  { id: 85, word: 'during', pos: '前置詞', meaning: '～の間（ずっと）' },
  { id: 86, word: 'each', pos: '代名詞', meaning: 'それぞれ、各々' },
  { id: 87, word: 'early', pos: '副詞', meaning: '早く / 形容詞：早い' },
  { id: 88, word: 'earn', pos: '動詞', meaning: '（お金を）稼ぐ、（評判を）得る' },
  { id: 89, word: 'easy', pos: '形容詞', meaning: '簡単な、容易な' },
  { id: 90, word: 'economy', pos: '名詞', meaning: '経済、節約' },
  { id: 91, word: 'education', pos: '名詞', meaning: '教育' },
  { id: 92, word: 'effect', pos: '名詞', meaning: '効果、影響、結果' },
  { id: 93, word: 'effort', pos: '名詞', meaning: '努力' },
  { id: 94, word: 'either', pos: '代名詞', meaning: '（2つのうちの）どちらか一方' },
  { id: 95, word: 'employee', pos: '名詞', meaning: '従業員、社員' },
  { id: 96, word: 'employer', pos: '名詞', meaning: '雇い主、雇用主' },
  { id: 97, word: 'employment', pos: '名詞', meaning: '雇用、職' },
  { id: 98, word: 'encourage', pos: '動詞', meaning: '励ます、促す' },
  { id: 99, word: 'end', pos: '名詞', meaning: '終わり、結末 / 動詞：終わる' },
  { id: 100, word: 'engine', pos: '名詞', meaning: 'エンジン' },
  { id: 101, word: 'equipment', pos: '名詞', meaning: '機器、設備' },
  { id: 102, word: 'executive', pos: '名詞', meaning: '重役、幹部' },
  { id: 103, word: 'expect', pos: '動詞', meaning: '予期する、期待する' },
  { id: 104, word: 'experience', pos: '名詞', meaning: '経験、体験' },
  { id: 105, word: 'expert', pos: '名詞', meaning: '専門家、熟練者' },
  { id: 106, word: 'explain', pos: '動詞', meaning: '説明する' },
  { id: 107, word: 'export', pos: '動詞', meaning: '輸出する' },
  { id: 108, word: 'express', pos: '動詞', meaning: '表現する' },
  { id: 109, word: 'factory', pos: '名詞', meaning: '工場' },
  { id: 110, word: 'fail', pos: '動詞', meaning: '失敗する、～し損なう' },
  { id: 111, word: 'fair', pos: '形容詞', meaning: '公平な、妥当な' },
  { id: 112, word: 'fall', pos: '動詞', meaning: '落ちる、下落する' },
  { id: 113, word: 'famous', pos: '形容詞', meaning: '有名な' },
  { id: 114, word: 'fast', pos: '形容詞', meaning: '速い / 副詞：速く' },
  { id: 115, word: 'favor', pos: '名詞', meaning: '親切な行為、お願い' },
  { id: 116, word: 'fax', pos: '名詞', meaning: 'ファックス' },
  { id: 117, word: 'fee', pos: '名詞', meaning: '料金、謝礼' },
  { id: 118, word: 'field', pos: '名詞', meaning: '分野、野原、競技場' },
  { id: 119, word: 'file', pos: '名詞', meaning: 'ファイル、書類綴り' },
  { id: 120, word: 'fill', pos: '動詞', meaning: '満たす、（用紙に）記入する' },
  { id: 121, word: 'final', pos: '形容詞', meaning: '最終の、最後の' },
  { id: 122, word: 'finance', pos: '名詞', meaning: '財政、金融、資金' },
  { id: 123, word: 'find', pos: '動詞', meaning: '見つける、～だとわかる' },
  { id: 124, word: 'fine', pos: '形容詞', meaning: '素晴らしい、元気な / 名詞：罰金' },
  { id: 125, word: 'finish', pos: '動詞', meaning: '終える、終わる' },
  { id: 126, word: 'firm', pos: '名詞', meaning: '会社、事務所' },
  { id: 127, word: 'first', pos: '形容詞・副詞', meaning: '最初の、最初に' },
  { id: 128, word: 'fix', pos: '動詞', meaning: '修理する、固定する、決定する' },
  { id: 129, word: 'floor', pos: '名詞', meaning: '床、（建物の）階' },
  { id: 130, word: 'fly', pos: '動詞', meaning: '飛ぶ、飛行機で行く' },
  { id: 131, word: 'follow', pos: '動詞', meaning: '従う、～に続く、理解する' },
  { id: 132, word: 'foreign', pos: '形容詞', meaning: '外国の' },
  { id: 133, word: 'forget', pos: '動詞', meaning: '忘れる' },
  { id: 134, word: 'form', pos: '名詞', meaning: '用紙、形 / 動詞：結成する、形づくる' },
  { id: 135, word: 'forward', pos: '副詞', meaning: '前方へ / 動詞：転送する' },
  { id: 136, word: 'free', pos: '形容詞', meaning: '無料の、自由な、暇な' },
  { id: 137, word: 'front', pos: '名詞', meaning: '前面、正面' },
  { id: 138, word: 'full', pos: '形容詞', meaning: '満員の、いっぱいの' },
  { id: 139, word: 'furniture', pos: '名詞', meaning: '家具' },
  { id: 140, word: 'future', pos: '名詞', meaning: '未来、将来' },
  { id: 141, word: 'gain', pos: '動詞', meaning: '得る、増す / 名詞：利益' },
  { id: 142, word: 'general', pos: '形容詞', meaning: '一般的な、全体の' },
  { id: 143, word: 'get', pos: '動詞', meaning: '手に入れる、受け取る、（ある状態に）なる' },
  { id: 144, word: 'give', pos: '動詞', meaning: '与える、あげる' },
  { id: 145, word: 'glad', pos: '形容詞', meaning: 'うれしい' },
  { id: 146, word: 'goal', pos: '名詞', meaning: '目標、ゴール' },
  { id: 147, word: 'government', pos: '名詞', meaning: '政府' },
  { id: 148, word: 'great', pos: '形容詞', meaning: '偉大な、素晴らしい' },
  { id: 149, word: 'ground', pos: '名詞', meaning: '地面、土地' },
  { id: 150, word: 'group', pos: '名詞', meaning: '集団、グループ' },
  { id: 151, word: 'grow', pos: '動詞', meaning: '成長する、育てる、増大する' },
  { id: 152, word: 'guarantee', pos: '動詞', meaning: '保証する / 名詞：保証（書）' },
  { id: 153, word: 'guess', pos: '動詞', meaning: '推測する' },
  { id: 154, word: 'guide', pos: '名詞', meaning: '案内者、ガイド / 動詞：案内する' },
  { id: 155, word: 'half', pos: '名詞', meaning: '半分（の）' },
  { id: 156, word: 'hand', pos: '名詞', meaning: '手 / 動詞：手渡す（hand inなど）' },
  { id: 157, word: 'handle', pos: '動詞', meaning: '扱う、処理する' },
  { id: 158, word: 'happen', pos: '動詞', meaning: '起こる、偶然～する' },
  { id: 159, word: 'hard', pos: '形容詞', meaning: '難しい、硬い / 副詞：一生懸命に' },
  { id: 160, word: 'head', pos: '名詞', meaning: '頭、頭取、長 / 動詞：向かう' },
  { id: 161, word: 'hear', pos: '動詞', meaning: '聞こえる、聞く' },
  { id: 162, word: 'heavy', pos: '形容詞', meaning: '重い' },
  { id: 163, word: 'help', pos: '動詞', meaning: '手伝う、助ける' },
  { id: 164, word: 'high', pos: '形容詞', meaning: '高い' },
  { id: 165, word: 'hire', pos: '動詞', meaning: '雇う' },
  { id: 166, word: 'hold', pos: '動詞', meaning: '持つ、開催する、維持する' },
  { id: 167, word: 'hope', pos: '動詞', meaning: '望む、期待する' },
  { id: 168, word: 'hour', pos: '名詞', meaning: '時間、1時間' },
  { id: 169, word: 'huge', pos: '形容詞', meaning: '巨大な' },
  { id: 170, word: 'human', pos: '形容詞', meaning: '人間の、人類の / 名詞：人間' },
  { id: 171, word: 'hurry', pos: '動詞', meaning: '急ぐ / 名詞：急ぎ' },
  { id: 172, word: 'idea', pos: '名詞', meaning: '考え、アイデア' },
  { id: 173, word: 'identify', pos: '動詞', meaning: '特定する、確認する' },
  { id: 174, word: 'illness', pos: '名詞', meaning: '病気' },
  { id: 175, word: 'image', pos: '名詞', meaning: '画像、イメージ、印象' },
  { id: 176, word: 'important', pos: '形容詞', meaning: '重要な' },
  { id: 177, word: 'improve', pos: '動詞', meaning: '改善する、上達する' },
  { id: 178, word: 'include', pos: '動詞', meaning: '含む' },
  { id: 179, word: 'income', pos: '名詞', meaning: '収入、所得' },
  { id: 180, word: 'increase', pos: '動詞', meaning: '増加する、増やす' },
  { id: 181, word: 'industry', pos: '名詞', meaning: '産業、工業' },
  { id: 182, word: 'information', pos: '名詞', meaning: '情報' },
  { id: 183, word: 'inside', pos: '前置詞・副詞', meaning: '内側に、中に' },
  { id: 184, word: 'instead', pos: '副詞', meaning: '代わりに' },
  { id: 185, word: 'instruction', pos: '名詞', meaning: '指示、説明書' },
  { id: 186, word: 'interest', pos: '名詞', meaning: '興味、利息' },
  { id: 187, word: 'international', pos: '形容詞', meaning: '国際的な' },
  { id: 188, word: 'interview', pos: '名詞', meaning: '面接、インタビュー' },
  { id: 189, word: 'introduce', pos: '動詞', meaning: '紹介する、導入する' },
  { id: 190, word: 'invent', pos: '動詞', meaning: '発明する' },
  { id: 191, word: 'invite', pos: '動詞', meaning: '招待する' },
  { id: 192, word: 'invoice', pos: '名詞', meaning: '送り状、請求明細書' },
  { id: 193, word: 'issue', pos: '名詞', meaning: '問題、（雑誌の）号' },
  { id: 194, word: 'item', pos: '名詞', meaning: '品目、項目、アイテム' },
  { id: 195, word: 'job', pos: '名詞', meaning: '仕事、職' },
  { id: 196, word: 'join', pos: '動詞', meaning: '参加する、加わる' },
  { id: 197, word: 'keep', pos: '動詞', meaning: '保つ、持ち続ける' },
  { id: 198, word: 'key', pos: '名詞', meaning: '鍵、手がかり' },
  { id: 199, word: 'kind', pos: '形容詞', meaning: '親切な / 名詞：種類' },
  { id: 200, word: 'knowledge', pos: '名詞', meaning: '知識' },
  { id: 201, word: 'laboratory', pos: '名詞', meaning: '実験室、研究所' },
  { id: 202, word: 'labor', pos: '名詞', meaning: '労働、労働力' },
  { id: 203, word: 'large', pos: '形容詞', meaning: '大きい、広い' },
  { id: 204, word: 'last', pos: '形容詞', meaning: '最後の、この前の / 動詞：続く' },
  { id: 205, word: 'late', pos: '形容詞・副詞', meaning: '遅い、遅れて' },
  { id: 206, word: 'law', pos: '名詞', meaning: '法律' },
  { id: 207, word: 'lead', pos: '動詞', meaning: '導く、率いる、つながる' },
  { id: 208, word: 'leader', pos: '名詞', meaning: '指導者、リーダー' },
  { id: 209, word: 'learn', pos: '動詞', meaning: '学ぶ、知る' },
  { id: 210, word: 'least', pos: '副詞・代名詞', meaning: '最も少なく（い）' },
  { id: 211, word: 'leave', pos: '動詞', meaning: '去る、出発する、残す、休暇をとる' },
  { id: 212, word: 'lend', pos: '動詞', meaning: '貸す' },
  { id: 213, word: 'less', pos: '副詞・形容詞', meaning: 'より少なく（い）' },
  { id: 214, word: 'letter', pos: '名詞', meaning: '手紙、文字' },
  { id: 215, word: 'level', pos: '名詞', meaning: '水準、レベル' },
  { id: 216, word: 'library', pos: '名詞', meaning: '図書館' },
  { id: 217, word: 'license', pos: '名詞', meaning: '免許증、ライセンス' },
  { id: 218, word: 'light', pos: '名詞', meaning: '光、照明 / 形容詞：軽い、明るい' },
  { id: 219, word: 'line', pos: '名詞', meaning: '線、列、（製品の）ライン' },
  { id: 220, word: 'list', pos: '名詞', meaning: 'リスト、一覧表 / 動詞：一覧表にする' },
  { id: 221, word: 'listen', pos: '動詞', meaning: '聴く、耳を傾ける' },
  { id: 222, word: 'local', pos: '形容詞', meaning: '地元の、地域の' },
  { id: 223, word: 'locate', pos: '動詞', meaning: '（場所を）特定する、位置させる' },
  { id: 224, word: 'long', pos: '形容詞', meaning: '長い' },
  { id: 225, word: 'look', pos: '動詞', meaning: '見る、～のように見える' },
  { id: 226, word: 'lose', pos: '動詞', meaning: '失う、負ける' },
  { id: 227, word: 'loss', pos: '名詞', meaning: '損失、失うこと' },
  { id: 228, word: 'low', pos: '形容詞', meaning: '低い' },
  { id: 229, word: 'machine', pos: '名詞', meaning: '機械' },
  { id: 230, word: 'magazine', pos: '名詞', meaning: '雑誌' },
  { id: 231, word: 'main', pos: '形容詞', meaning: '主な、主要な' },
  { id: 232, word: 'make', pos: '動詞', meaning: '作る、（ある状態に）する' },
  { id: 233, word: 'manage', pos: '動詞', meaning: 'なんとかやり遂げる、管理する、経営する' },
  { id: 234, word: 'manager', pos: '名詞', meaning: '経営者、マネージャー、課長' },
  { id: 235, word: 'manner', pos: '名詞', meaning: '方法、マナー、行儀' },
  { id: 236, word: 'manufacture', pos: '動詞', meaning: '製造する / 名詞：製造' },
  { id: 237, word: 'many', pos: '形容詞', meaning: '多くの' },
  { id: 238, word: 'market', pos: '名詞', meaning: '市場' },
  { id: 239, word: 'material', pos: '名詞', meaning: '材料、素材、資料' },
  { id: 240, word: 'matter', pos: '名詞', meaning: '問題、事柄 / 動詞：重要である' },
  { id: 241, word: 'mean', pos: '動詞', meaning: '意味する' },
  { id: 242, word: 'measure', pos: '動詞', meaning: '測る / 名詞：対策、手段' },
  { id: 243, word: 'media', pos: '名詞', meaning: 'メディア、媒体' },
  { id: 244, word: 'medical', pos: '形容詞', meaning: '医学の、医療の' },
  { id: 245, word: 'meet', pos: '動詞', meaning: '会う、（要求などを）満たす' },
  { id: 246, word: 'meeting', pos: '名詞', meaning: '会議、ミーティング' },
  { id: 247, word: 'member', pos: '名詞', meaning: '会員、メンバー' },
  { id: 248, word: 'mention', pos: '動詞', meaning: '言及する、口にする' },
  { id: 249, word: 'message', pos: '名詞', meaning: '伝言、メッセージ' },
  { id: 250, word: 'method', pos: '名詞', meaning: '方法、手法' },
  { id: 251, word: 'middle', pos: '名詞・形容詞', meaning: '中央（の）、真ん中（の）' },
  { id: 252, word: 'mind', pos: '名詞', meaning: '心、精神 / 動詞：気にする' },
  { id: 253, word: 'minute', pos: '名詞', meaning: '分、（会議の）議事録（minutes）' },
  { id: 254, word: 'miss', pos: '動詞', meaning: '逃す、寂しく思う' },
  { id: 255, word: 'mistake', pos: '名詞', meaning: '間違い、ミス' },
  { id: 256, word: 'modern', pos: '形容詞', meaning: '現代的な、近代的な' },
  { id: 257, word: 'moment', pos: '名詞', meaning: '瞬間、少しの間' },
  { id: 258, word: 'money', pos: '名詞', meaning: 'お金' },
  { id: 259, word: 'month', pos: '名詞', meaning: '1ヶ月' },
  { id: 260, word: 'move', pos: '動詞', meaning: '動く、引っ越す、感動させる' },
  { id: 261, word: 'national', pos: '形容詞', meaning: '国家の、全国的な' },
  { id: 262, word: 'natural', pos: '形容詞', meaning: '自然の、当然の' },
  { id: 263, word: 'near', pos: '前置詞', meaning: '～の近くに' },
  { id: 264, word: 'necessary', pos: '形容詞', meaning: '必要な' },
  { id: 265, word: 'need', pos: '動詞', meaning: '～を必要とする / 名詞：必要性' },
  { id: 266, word: 'neighborhood', pos: '名詞', meaning: '近所、地域' },
  { id: 267, word: 'new', pos: '形容詞', meaning: '新しい' },
  { id: 268, word: 'news', pos: '名詞', meaning: 'ニュース、知らせ' },
  { id: 269, word: 'next', pos: '形容詞', meaning: '次の / 副詞：次に' },
  { id: 270, word: 'nice', pos: '形容詞', meaning: '良い、親切な' },
  { id: 271, word: 'night', pos: '名詞', meaning: '夜' },
  { id: 272, word: 'note', pos: '名詞', meaning: 'メモ、注釈 / 動詞：注意する、書き留める' },
  { id: 273, word: 'notice', pos: '名詞', meaning: '通知、掲示 / 動詞：気づく' },
  { id: 274, word: 'number', pos: '名詞', meaning: '数字、番号、数' },
  { id: 275, word: 'object', pos: '名詞', meaning: '物体、目的 / 動詞：反対する' },
  { id: 276, word: 'obtain', pos: '動詞', meaning: '得る、獲得する' },
  { id: 277, word: 'obvious', pos: '形容詞', meaning: '明らかな' },
  { id: 278, word: 'occasion', pos: '名詞', meaning: '機会、行事' },
  { id: 279, word: 'occupation', pos: '名詞', meaning: '職業' },
  { id: 280, word: 'offer', pos: '動詞', meaning: '提供する、申し出る' },
  { id: 281, word: 'office', pos: '名詞', meaning: '事務所、オフィス' },
  { id: 282, word: 'officer', pos: '名詞', meaning: '役員、公務員、警察官' },
  { id: 283, word: 'official', pos: '形容詞', meaning: '公式の、公の' },
  { id: 284, word: 'often', pos: '副詞', meaning: 'しばしば、よく' },
  { id: 285, word: 'old', pos: '形容詞', meaning: '古い、年をとった' },
  { id: 286, word: 'once', pos: '副詞', meaning: 'かつて、一度' },
  { id: 287, word: 'online', pos: '形容詞・副詞', meaning: 'オンラインの（で）' },
  { id: 288, word: 'open', pos: '動詞', meaning: '開ける、開く / 形容詞：開いている' },
  { id: 289, word: 'operate', pos: '動詞', meaning: '操作する、運営する、営業する' },
  { id: 290, word: 'opinion', pos: '名詞', meaning: '意見' },
  { id: 291, word: 'opportunity', pos: '名詞', meaning: '機会、チャンス' },
  { id: 292, word: 'order', pos: '名詞', meaning: '注文、順序、秩序 / 動詞：注文する' },
  { id: 293, word: 'organization', pos: '名詞', meaning: '組織、団体' },
  { id: 294, word: 'original', pos: '形容詞', meaning: '独自の、最初の、オリジナルの' },
  { id: 295, word: 'other', pos: '形容詞・代名詞', meaning: '他の、別の人（物）' },
  { id: 296, word: 'outside', pos: '前置詞・副詞', meaning: '外側に、屋外で' },
  { id: 297, word: 'own', pos: '動詞', meaning: '所有する' },
  { id: 298, word: 'owner', pos: '名詞', meaning: '所有者、オーナー' },
  { id: 299, word: 'package', pos: '名詞', meaning: '小包、パッケージ' },
  { id: 300, word: 'page', pos: '名詞', meaning: 'ページ' }
];

export default WORDS;
