const WORDS = [
  { id: 1, word: 'accounting', pos: '名詞', meaning: '会計、経理' },
  { id: 2, word: 'additional', pos: '形容詞', meaning: '追加の' },
  { id: 3, word: 'address', pos: '動詞', meaning: '（問題などに）取り組む、話しかける / 名詞：住所' },
  { id: 4, word: 'agenda', pos: '名詞', meaning: '協議事項、議題、アジェンダ' },
  { id: 5, word: 'agreement', pos: '名詞', meaning: '合意、契約、協定' },
  { id: 6, word: 'annual', pos: '形容詞', meaning: '年に一度の、例年の' },
  { id: 7, word: 'applicant', pos: '名詞', meaning: '応募者、志願者' },
  { id: 8, word: 'approve', pos: '動詞', meaning: '承認する、賛成する' },
  { id: 9, word: 'assets', pos: '名詞', meaning: '資産、財産' },
  { id: 10, word: 'assignment', pos: '名詞', meaning: '割り当てられた仕事、課題' },
  { id: 11, word: 'audience', pos: '名詞', meaning: '聴衆、観客' },
  { id: 12, word: 'beverage', pos: '名詞', meaning: '飲料、飲み物' },
  { id: 13, word: 'brochure', pos: '名詞', meaning: 'パンフレット、小冊子' },
  { id: 14, word: 'budget', pos: '名詞', meaning: '予算 / 動詞：予算を立てる' },
  { id: 15, word: 'client', pos: '名詞', meaning: '顧客、クライアント' },
  { id: 16, word: 'colleague', pos: '名詞', meaning: '同僚' },
  { id: 17, word: 'committee', pos: '名詞', meaning: '委員会' },
  { id: 18, word: 'commute', pos: '動詞', meaning: '通勤する、通学する' },
  { id: 19, word: 'complimentary', pos: '形容詞', meaning: '無料の、招待の、お世辞の' },
  { id: 20, word: 'conduct', pos: '動詞', meaning: '（調査などを）行う、実施する' },
  { id: 21, word: 'conference', pos: '名詞', meaning: '会議、カンファレンス' },
  { id: 22, word: 'current', pos: '形容詞', meaning: '現在の、最新の' },
  { id: 23, word: 'deadline', pos: '名詞', meaning: '締め切り、納期' },
  { id: 24, word: 'decade', pos: '名詞', meaning: '10年間' },
  { id: 25, word: 'defect', pos: '名詞', meaning: '欠陥、不具合' },
  { id: 26, word: 'description', pos: '名詞', meaning: '説明、描写、解説' },
  { id: 27, word: 'destination', pos: '名詞', meaning: '目的地、行き先' },
  { id: 28, word: 'device', pos: '名詞', meaning: '装置、機器、デバイス' },
  { id: 29, word: 'discount', pos: '名詞', meaning: '割引 / 動詞：割引する' },
  { id: 30, word: 'document', pos: '名詞', meaning: '書類、文書 / 動詞：記録する' },
  { id: 31, word: 'efficient', pos: '形容詞', meaning: '効率的な、能率的な' },
  { id: 32, word: 'estimate', pos: '名詞', meaning: '見積もり（書） / 動詞：見積もる' },
  { id: 33, word: 'executive', pos: '名詞', meaning: '役員、重役 / 形容詞：管理職の' },
  { id: 34, word: 'facility', pos: '名詞', meaning: '施設、設備' },
  { id: 35, word: 'financial', pos: '形容詞', meaning: '財政上の、金融の' },
  { id: 36, word: 'frequently', pos: '副詞', meaning: '頻繁に、しばしば' },
  { id: 37, word: 'headquarters', pos: '名詞', meaning: '本社、本部' },
  { id: 38, word: 'implement', pos: '動詞', meaning: '（計画などを）実行する、実施する' },
  { id: 39, word: 'inventory', pos: '名詞', meaning: '在庫（目録）、棚卸し' },
  { id: 40, word: 'invoice', pos: '名詞', meaning: '請求書、送り状' },
  { id: 41, word: 'laboratory', pos: '名詞', meaning: '研究所、実験室' },
  { id: 42, word: 'negotiate', pos: '動詞', meaning: '交渉する' },
  { id: 43, word: 'notify', pos: '動詞', meaning: '通知する、知らせる' },
  { id: 44, word: 'passenger', pos: '名詞', meaning: '乗客' },
  { id: 45, word: 'permission', pos: '名詞', meaning: '許可、呼諾' },
  { id: 46, word: 'policy', pos: '名詞', meaning: '方針、政策、規約、保険証券' },
  { id: 47, word: 'procedure', pos: '名詞', meaning: '手続き、手順' },
  { id: 48, word: 'receipt', pos: '名詞', meaning: '領収書、レシート、受領' },
  { id: 49, word: 'refund', pos: '名詞', meaning: '返金、払い戻し / 動詞：返金する' },
  { id: 50, word: 'representative', pos: '名詞', meaning: '担当者、代表者 / 形容詞：代表的な' },
  { id: 51, word: 'accept', pos: '動詞', meaning: '受け入れる、承認する' },
  { id: 52, word: 'access', pos: '名詞', meaning: '利用する権利、接近 / 動詞：アクセスする' },
  { id: 53, word: 'accommodate', pos: '動詞', meaning: '収容する、宿泊させる、適応させる' },
  { id: 54, word: 'accomplish', pos: '動詞', meaning: '成し遂げる、達成する' },
  { id: 55, word: 'accordingly', pos: '副詞', meaning: 'それに応じて、したがって' },
  { id: 56, word: 'accurate', pos: '形容詞', meaning: '正確な、精密な' },
  { id: 57, word: 'achieve', pos: '動詞', meaning: '達成する、獲得する' },
  { id: 58, word: 'acquire', pos: '動詞', meaning: '買収する、得る、獲得する' },
  { id: 59, word: 'adjust', pos: '動詞', meaning: '調整する、合わせる、慣れる' },
  { id: 60, word: 'administration', pos: '名詞', meaning: '管理、経営、行政' },
  { id: 61, word: 'admire', pos: '動詞', meaning: '賞賛する、感心する' },
  { id: 62, word: 'admission', pos: '名詞', meaning: '入場（料）、入会、認めること' },
  { id: 63, word: 'advance', pos: '名詞', meaning: '進歩、前進 / 形容詞：事前の' },
  { id: 64, word: 'advertise', pos: '動詞', meaning: '広告を出す、宣伝する' },
  { id: 65, word: 'advice', pos: '名詞', meaning: '助言、アドバイス' },
  { id: 66, word: 'advise', pos: '動詞', meaning: '助言する、忠告する' },
  { id: 67, word: 'afford', pos: '動詞', meaning: '～する余裕がある' },
  { id: 68, word: 'agency', pos: '名詞', meaning: '代理店、機関' },
  { id: 69, word: 'aim', pos: '動詞', meaning: '目指す、狙う / 名詞：目的、目標' },
  { id: 70, word: 'airline', pos: '名詞', meaning: '航空会社' },
  { id: 71, word: 'aisle', pos: '名詞', meaning: '通路' },
  { id: 72, word: 'allow', pos: '動詞', meaning: '許可する、可能にする' },
  { id: 73, word: 'alter', pos: '動詞', meaning: '変更する、変える' },
  { id: 74, word: 'alternative', pos: '名詞', meaning: '代わりのもの、選択肢 / 形容詞：代わりの' },
  { id: 75, word: 'announce', pos: '動詞', meaning: '発表する、告知する' },
  { id: 76, word: 'anxious', pos: '形容詞', meaning: '心配して、切望して' },
  { id: 77, word: 'apologize', pos: '動詞', meaning: '謝罪する、お詫びする' },
  { id: 78, word: 'appliance', pos: '名詞', meaning: '（家庭用の）電化製品、器具' },
  { id: 79, word: 'application', pos: '名詞', meaning: '応募、申請、適用、アプリ' },
  { id: 80, word: 'appoint', pos: '動詞', meaning: '指名する、任命する' },
  { id: 81, word: 'appointment', pos: '名詞', meaning: '（面会の）約束、予約、任命' },
  { id: 82, word: 'appreciate', pos: '動詞', meaning: '感謝する、正しく評価する' },
  { id: 83, word: 'approach', pos: '名詞', meaning: 'アプローチ、近づく方法 / 動詞：近づく' },
  { id: 84, word: 'appropriate', pos: '形容詞', meaning: '適切な、ふさわしい' },
  { id: 85, word: 'architect', pos: '名詞', meaning: '建築家、設計者' },
  { id: 86, word: 'architecture', pos: '名詞', meaning: '建築（学）、構造' },
  { id: 87, word: 'arrange', pos: '動詞', meaning: '手配する、配置する、並べる' },
  { id: 88, word: 'arrangement', pos: '名詞', meaning: '手配、準備、配置' },
  { id: 89, word: 'arrival', pos: '名詞', meaning: '到着、到着したもの' },
  { id: 90, word: 'article', pos: '名詞', meaning: '記事、品物、条項' },
  { id: 91, word: 'aside', pos: '副詞', meaning: '脇に、別にして' },
  { id: 92, line: 'aspect', pos: '名詞', meaning: '側面、局面' },
  { id: 93, word: 'assemble', pos: '動詞', meaning: '組み立てる、集まる' },
  { id: 94, word: 'assembly', pos: '名詞', meaning: '組み立て、集会' },
  { id: 95, word: 'assess', pos: '動詞', meaning: '評価する、査定する' },
  { id: 96, word: 'asset', pos: '名詞', meaning: '資産、強み' },
  { id: 97, word: 'assign', pos: '動詞', meaning: '割り当てる、配属する' },
  { id: 98, word: 'assist', pos: '動詞', meaning: '手伝う、援助する' },
  { id: 99, word: 'assistance', pos: '名詞', meaning: '援助、支援' },
  { id: 100, word: 'assistant', pos: '名詞', meaning: '助手、アシスタント / 形容詞：補佐の' },
  { id: 101, word: 'associate', pos: '動詞', meaning: '関連づける、交際する / 名詞：同僚、仲間' },
  { id: 102, word: 'association', pos: '名詞', meaning: '協会、組合、関連' },
  { id: 103, word: 'assume', pos: '動詞', meaning: '引き受ける、想定する、思い込む' },
  { id: 104, word: 'assurance', pos: '名詞', meaning: '確約、保証、自信' },
  { id: 105, word: 'assure', pos: '動詞', meaning: '保証する、請け合う' },
  { id: 106, word: 'attach', pos: '動詞', meaning: '添付する、貼り付ける' },
  { id: 107, word: 'attachment', pos: '名詞', meaning: '添付ファイル、付属品' },
  { id: 108, word: 'attain', pos: '動詞', meaning: '達成する、到達する' },
  { id: 109, word: 'attempt', pos: '動詞', meaning: '試みる、企てる / 名詞：試み' },
  { id: 110, word: 'attend', pos: '動詞', meaning: '出席する、参加する、注意を払う' },
  { id: 111, word: 'attendance', pos: '名詞', meaning: '出席、出席者数' },
  { id: 112, word: 'attendant', pos: '名詞', meaning: '係員、案内係' },
  { id: 113, word: 'attitude', pos: '名詞', meaning: '態度、心構え' },
  { id: 114, word: 'attract', pos: '動詞', meaning: '（引き）つける、魅了する' },
  { id: 115, word: 'attraction', pos: '名詞', meaning: '観光名所、魅力' },
  { id: 116, word: 'attractive', pos: '形容詞', meaning: '魅力的な' },
  { id: 117, word: 'attribute', pos: '動詞', meaning: '～のせいにする / 名詞：特性、属性' },
  { id: 118, word: 'author', pos: '名詞', meaning: '著者、作者' },
  { id: 119, word: 'authority', pos: '名詞', meaning: '権限、権威、当局' },
  { id: 120, word: 'authorize', pos: '動詞', meaning: '公認する、権限を与える' },
  { id: 121, word: 'available', pos: '形容詞', meaning: '手に入る、利用できる、時間が空いている' },
  { id: 122, word: 'avenue', pos: '名詞', meaning: '大通り、手段' },
  { id: 123, word: 'avoid', pos: '動詞', meaning: '避ける、回避する' },
  { id: 124, word: 'award', pos: '名詞', meaning: '賞 / 動詞：授与する' },
  { id: 125, word: 'aware', pos: '形容詞', meaning: '気づいて、知って' },
  { id: 126, word: 'awareness', pos: '名詞', meaning: '意識、認識' },
  { id: 127, word: 'banquet', pos: '名詞', meaning: '宴会、晩餐会' },
  { id: 128, word: 'bargain', pos: '名詞', meaning: 'お買い得品、取引 / 動詞：交渉する' },
  { id: 129, word: 'barrier', pos: '名詞', meaning: '障壁、防壁' },
  { id: 130, word: 'base', pos: '動詞', meaning: '拠点を置く、基づかせる / 名詞：土台' },
  { id: 131, word: 'basic', pos: '形容詞', meaning: '基本的な、基礎的な' },
  { id: 132, word: 'basically', pos: '副詞', meaning: '基本的に、要するに' },
  { id: 133, word: 'benefit', pos: '名詞', meaning: '利益、特典、福利厚生 / 動詞：利益を得る' },
  { id: 134, word: 'bill', pos: '名詞', meaning: '請求書、法案、紙幣' },
  { id: 135, word: 'board', pos: '名詞', meaning: '取締役会、掲示板 / 動詞：搭乗する' },
  { id: 136, word: 'boardroom', pos: '名詞', meaning: '役員室、会議室' },
  { id: 137, word: 'boast', pos: '動詞', meaning: '誇る、自慢する' },
  { id: 138, word: 'book', pos: '動詞', meaning: '予約する / 名詞：本' },
  { id: 139, word: 'booking', pos: '名詞', meaning: '予約' },
  { id: 140, word: 'boost', pos: '動詞', meaning: '高める、押し上げる / 名詞：上昇、促進' },
  { id: 141, word: 'borrow', pos: '動詞', meaning: '借りる' },
  { id: 142, word: 'boss', pos: '名詞', meaning: '上司、ボス' },
  { id: 143, word: 'bother', pos: '動詞', meaning: '悩ませる、わざわざ～する' },
  { id: 144, word: 'bottom', pos: '名詞', meaning: '底、最下位' },
  { id: 145, word: 'branch', pos: '名詞', meaning: '支店、枝' },
  { id: 146, word: 'brand', pos: '名詞', meaning: 'ブランド、銘柄' },
  { id: 147, word: 'brief', pos: '形容詞', meaning: '簡潔な、短い' },
  { id: 148, word: 'briefly', pos: '副詞', meaning: '簡潔に、短時間' },
  { id: 149, word: 'broad', pos: '形容詞', meaning: '広い、広範囲に及ぶ' },
  { id: 150, word: 'broadcast', pos: '動詞', meaning: '放送する / 名詞：放送' },
  { id: 151, word: 'browse', pos: '動詞', meaning: '（ウェブなどを）閲覧する、拾い読みする' },
  { id: 152, word: 'builder', pos: '名詞', meaning: '建築業者' },
  { id: 153, word: 'burden', pos: '名詞', meaning: '負担、重荷' },
  { id: 154, word: 'business', pos: '名詞', meaning: 'ビジネス、事業、商売' },
  { id: 155, word: 'calculate', pos: '動詞', meaning: '計算する、予測する' },
  { id: 156, word: 'calculation', pos: '名詞', meaning: '計算、見積もり' },
  { id: 157, word: 'campaign', pos: '名詞', meaning: 'キャンペーン、運動' },
  { id: 158, word: 'cancel', pos: '動詞', meaning: 'キャンセルする、取り消す' },
  { id: 159, word: 'cancellation', pos: '名詞', meaning: 'キャンセル、取り消し' },
  { id: 160, word: 'candidate', pos: '名詞', meaning: '候補者、志願者' },
  { id: 161, word: 'capable', pos: '形容詞', meaning: '能力がある、有能な' },
  { id: 162, word: 'capacity', pos: '名詞', meaning: '収容能力、容量、能力' },
  { id: 163, word: 'capital', pos: '名詞', meaning: '資本（金）、首都' },
  { id: 164, word: 'career', pos: '名詞', meaning: '経歴、キャリア' },
  { id: 165, word: 'cargo', pos: '名詞', meaning: '貨物、積荷' },
  { id: 166, word: 'cash', pos: '名詞', meaning: '現金 / 動詞：現金に換える' },
  { id: 167, word: 'cashier', pos: '名詞', meaning: 'レジ係、会計係' },
  { id: 168, word: 'casual', pos: '形容詞', meaning: '略式の、何気ない、偶然の' },
  { id: 169, word: 'catalog', pos: '名詞', meaning: 'カタログ、目録' },
  { id: 170, word: 'cater', pos: '動詞', meaning: '（料理を）仕出す、要求を満たす' },
  { id: 171, word: 'celebrate', pos: '動詞', meaning: '祝う、称える' },
  { id: 172, word: 'celebration', pos: '名詞', meaning: 'お祝い、祝典' },
  { id: 173, word: 'celebrity', pos: '名詞', meaning: '有名人、著名人' },
  { id: 174, word: 'center', pos: '名詞', meaning: '中心、センター' },
  { id: 175, word: 'central', pos: '形容詞', meaning: '中央の、中心的な' },
  { id: 176, word: 'century', pos: '名詞', meaning: '1世紀、100年' },
  { id: 177, word: 'ceremony', pos: '名詞', meaning: '式典、儀式' },
  { id: 178, word: 'certificate', pos: '名詞', meaning: '証明書、免許状' },
  { id: 179, word: 'chair', pos: '名詞', meaning: '議長、椅子 / 動詞：議長を務める' },
  { id: 180, word: 'chairman', pos: '名詞', meaning: '議長、会長' },
  { id: 181, word: 'challenge', pos: '名詞', meaning: '課題、挑戦 / 動詞：異議を唱える' },
  { id: 182, word: 'chamber', pos: '名詞', meaning: '（特設の）会議場、部屋' },
  { id: 183, word: 'chance', pos: '名詞', meaning: '機会、可能性、見込み' },
  { id: 184, word: 'change', pos: '動詞', meaning: '変える / 名詞：変化、おつり' },
  { id: 185, word: 'charge', pos: '名詞', meaning: '料金、責任 / 動詞：請求する、充電する' },
  { id: 186, word: 'charity', pos: '名詞', meaning: '慈善（団体）' },
  { id: 187, word: 'chart', pos: '名詞', meaning: '図表、グラフ' },
  { id: 188, word: 'cheap', pos: '形容詞', meaning: '安い、安っぽい' },
  { id: 189, word: 'check', pos: '動詞', meaning: '確認する / 名詞：検査、小切手' },
  { id: 190, word: 'chef', pos: '名詞', meaning: '料理長、シェフ' },
  { id: 191, word: 'chemical', pos: '名詞', meaning: '化学物質 / 形容詞：化学の' },
  { id: 192, word: 'chief', pos: '形容詞', meaning: '主要な、最高位の / 名詞：長、上司' },
  { id: 193, word: 'choice', pos: '名詞', meaning: '選択、選択肢' },
  { id: 194, word: 'choose', pos: '動詞', meaning: '選ぶ、選択する' },
  { id: 195, word: 'chronological', pos: '形容詞', meaning: '年代順の' },
  { id: 196, word: 'circulate', pos: '動詞', meaning: '配布する、循環する' },
  { id: 197, word: 'circulation', pos: '名詞', meaning: '（発行）部数、循環、流通' },
  { id: 198, word: 'circumstance', pos: '名詞', meaning: '状況、事情' },
  { id: 199, word: 'citizen', pos: '名詞', meaning: '市民、国民' },
  { id: 200, word: 'city', pos: '名詞', meaning: '都市、市' },
  { id: 201, word: 'claim', pos: '動詞', meaning: '主張する、請求する / 名詞：主張、請求' },
  { id: 202, word: 'clarify', pos: '動詞', meaning: '明確にする、分かりやすくする' },
  { id: 203, word: 'clarity', pos: '名詞', meaning: '明確さ、透明さ' },
  { id: 204, word: 'class', pos: '名詞', meaning: 'クラス、授業、階級' },
  { id: 205, word: 'classic', pos: '形容詞', meaning: '定番の、最高水準の' },
  { id: 206, word: 'classification', pos: '名詞', meaning: '分類、区分' },
  { id: 207, word: 'classify', pos: '動詞', meaning: '分類する' },
  { id: 208, word: 'clause', pos: '名詞', meaning: '（条約などの）条項、節' },
  { id: 209, word: 'clear', pos: '形容詞', meaning: '明確な、澄んだ / 動詞：片付ける' },
  { id: 210, word: 'clearly', pos: '副詞', meaning: '明らかに、はっきりと' },
  { id: 211, word: 'clerk', pos: '名詞', meaning: '事務員、店員' },
  { id: 212, word: 'climate', pos: '名詞', meaning: '気候、風潮' },
  { id: 213, word: 'clinic', pos: '名詞', meaning: '診療所、クリニック' },
  { id: 214, word: 'close', pos: '形容詞', meaning: '近い、親しい / 動詞：閉める' },
  { id: 215, word: 'closely', pos: '副詞', meaning: '密接に、注意深く' },
  { id: 216, word: 'closure', pos: '名詞', meaning: '閉鎖、閉店' },
  { id: 217, word: 'clothing', pos: '名詞', meaning: '衣類、衣服' },
  { id: 218, word: 'coach', pos: '名詞', meaning: 'コーチ、大型バス、普通客車' },
  { id: 219, word: 'code', pos: '名詞', meaning: '規則、暗号、コード' },
  { id: 220, word: 'cognitive', pos: '形容詞', meaning: '認知の、認識の' },
  { id: 221, word: 'coincide', pos: '動詞', meaning: '同時に起こる、一致する' },
  { id: 222, word: 'coincidence', pos: '名詞', meaning: '偶然の一致' },
  { id: 223, word: 'collaborate', pos: '動詞', meaning: '協力する、共同で行う' },
  { id: 224, word: 'collaboration', pos: '名詞', meaning: '協力、協同' },
  { id: 225, word: 'collaborative', pos: '形容詞', meaning: '協力的な、共同の' },
  { id: 226, word: 'collapse', pos: '動詞', meaning: '崩壊する、倒れる / 名詞：崩壊' },
  { id: 227, word: 'collect', pos: '動詞', meaning: '集める、回収する' },
  { id: 228, word: 'collection', pos: '名詞', meaning: '収集（品）、回収、コレクション' },
  { id: 229, word: 'collective', pos: '形容詞', meaning: '集団の、共同の' },
  { id: 230, word: 'combination', pos: '名詞', meaning: '組み合わせ、結合' },
  { id: 231, word: 'combine', pos: '動詞', meaning: '組み合わせる、結合する' },
  { id: 232, word: 'comfortable', pos: '形容詞', meaning: '快適な、心地よい' },
  { id: 233, word: 'command', pos: '名詞', meaning: '命令、指揮（能力） / 動詞：命令する' },
  { id: 234, word: 'commence', pos: '動詞', meaning: '始まる、開始する' },
  { id: 235, word: 'commend', pos: '動詞', meaning: '褒める、称賛する' },
  { id: 236, word: 'comment', pos: '名詞', meaning: '意見、コメント / 動詞：批評する' },
  { id: 237, word: 'commerce', pos: '名詞', meaning: '商業、通商' },
  { id: 238, word: 'commercial', pos: '形容詞', meaning: '商業的な、商業の / 名詞：CM' },
  { id: 239, word: 'commission', pos: '名詞', meaning: '委員会、手数料、委託' },
  { id: 240, word: 'commit', pos: '動詞', meaning: 'コミットする、委ねる、犯す' },
  { id: 241, word: 'commitment', pos: '名詞', meaning: '約束、献身、関与' },
  { id: 242, word: 'commodity', pos: '名詞', meaning: '商品、日用品、産物' },
  { id: 243, word: 'common', pos: '形容詞', meaning: '共通の、一般的な、普通の' },
  { id: 244, word: 'commonly', pos: '副詞', meaning: '一般に、通常' },
  { id: 245, word: 'communicate', pos: '動詞', meaning: '伝える、意思疎通する' },
  { id: 246, word: 'communication', pos: '名詞', meaning: 'コミュニケーション、通信' },
  { id: 247, word: 'community', pos: '名詞', meaning: '地域社会、コミュニティ' },
  { id: 248, word: 'company', pos: '名詞', meaning: '会社、同伴、仲間' },
  { id: 249, word: 'comparable', pos: '形容詞', meaning: '比較できる、匹敵する' },
  { id: 250, word: 'comparative', pos: '形容詞', meaning: '比較の、相対的な' },
  { id: 251, word: 'comparatively', pos: '副詞', meaning: '比較的に、割合に' },
  { id: 252, word: 'compare', pos: '動詞', meaning: '比較する、たとえる' },
  { id: 253, word: 'comparison', pos: '名詞', meaning: '比較、対比' },
  { id: 254, word: 'compel', pos: '動詞', meaning: '強制する、強いる' },
  { id: 255, word: 'compensate', pos: '動詞', meaning: '補償する、埋め合わせる' },
  { id: 256, word: 'compensation', pos: '名詞', meaning: '補償（金）、報酬' },
  { id: 257, word: 'compete', pos: '動詞', meaning: '競う、競争する' },
  { id: 258, word: 'competence', pos: '名詞', meaning: '能力、適性' },
  { id: 259, word: 'competent', pos: '形容詞', meaning: '有能な、適任の' },
  { id: 260, word: 'competition', pos: '名詞', meaning: '競争、コンテスト、競合相手' },
  { id: 261, word: 'competitive', pos: '形容詞', meaning: '競争力のある、格安の、競争の' },
  { id: 262, word: 'competitor', pos: '名詞', meaning: '競合相手、競争者' },
  { id: 263, word: 'complain', pos: '動詞', meaning: '不満を言う、苦情を申し立てる' },
  { id: 264, word: 'complaint', pos: '名詞', meaning: '苦情、クレーム、不満' },
  { id: 265, word: 'complete', pos: '形容詞', meaning: '完全な、完了した / 動詞：完了させる' },
  { id: 266, word: 'completely', pos: '副詞', meaning: '完全に、まったく' },
  { id: 267, word: 'completion', pos: '名詞', meaning: '完了、完成' },
  { id: 268, word: 'complex', pos: '形容詞', meaning: '複雑な / 名詞：複合施設' },
  { id: 269, word: 'complexity', pos: '名詞', meaning: '複雑さ' },
  { id: 270, word: 'compliance', pos: '名詞', meaning: '（法令）順守、コンプライアンス' },
  { id: 271, word: 'comply', pos: '動詞', meaning: '従う、順守する' },
  { id: 272, word: 'component', pos: '名詞', meaning: '部品、構成要素' },
  { id: 273, word: 'compose', pos: '動詞', meaning: '構成する、作曲する' },
  { id: 274, word: 'composer', pos: '名詞', meaning: '作曲家' },
  { id: 275, word: 'composition', pos: '名詞', meaning: '構成、作文、楽曲' },
  { id: 276, word: 'comprehensive', pos: '形容詞', meaning: '包括的な、総合的な' },
  { id: 277, word: 'compromise', pos: '名詞', meaning: '妥協 / 動詞：妥協する' },
  { id: 278, word: 'compulsory', pos: '形容詞', meaning: '義務的な、強制的な' },
  { id: 279, word: 'conceal', pos: '動詞', meaning: '隠す、秘密にする' },
  { id: 280, word: 'concede', pos: '動詞', meaning: '認める、譲歩する' },
  { id: 281, word: 'conceive', pos: '動詞', meaning: '思いつく、想像する' },
  { id: 282, word: 'concentrate', pos: '動詞', meaning: '集中する' },
  { id: 283, word: 'concentration', pos: '名詞', meaning: '集中、濃度' },
  { id: 284, word: 'concept', pos: '名詞', meaning: '概念、コンセプト' },
  { id: 285, word: 'concern', pos: '名詞', meaning: '懸念、関心事 / 動詞：心配させる、関係する' },
  { id: 286, word: 'concerned', pos: '形容詞', meaning: '心配して、関わっている' },
  { id: 287, word: 'concerning', pos: '前置詞', meaning: '～に関する' },
  { id: 288, word: 'concert', pos: '名詞', meaning: 'コンサート、演奏会' },
  { id: 289, word: 'concession', pos: '名詞', meaning: '譲歩、売店' },
  { id: 290, word: 'concise', pos: '形容詞', meaning: '簡潔な' },
  { id: 291, word: 'conclude', pos: '動詞', meaning: '結論づける、締めくくる' },
  { id: 292, word: 'conclusion', pos: '名詞', meaning: '結論、結び' },
  { id: 293, word: 'conclusive', pos: '形容詞', meaning: '決定的な、決定づける' },
  { id: 294, word: 'concrete', pos: '形容詞', meaning: '具体的な / 名詞：コンクリート' },
  { id: 295, word: 'condition', pos: '名詞', meaning: '条件、状態、状況' },
  { id: 296, word: 'conditional', pos: '形容詞', meaning: '条件付きの' },
  { id: 297, word: 'condone', pos: '動詞', meaning: '容認する、許す' },
  { id: 298, word: 'conducive', pos: '形容詞', meaning: '～に貢献する、良い影響をもたらす' },
  { id: 299, word: 'confidential', pos: '形容詞', meaning: '機密の、秘密の' },
  { id: 300, word: 'confirm', pos: '動詞', meaning: '確認する、裏付ける'}
];

export default WORDS;