const WORDS = [
  { id: 1, word: 'accumulate', pos: '動詞', meaning: '蓄積する、ためる' },
  { id: 2, word: 'acquisition', pos: '名詞', meaning: '（企業の）買収、獲得' },
  { id: 3, word: 'adhere', pos: '動詞', meaning: '（規則などを）順守する、固執する' },
  { id: 4, word: 'adverse', pos: '形容詞', meaning: '逆の、不都合な、悪影響を及ぼす' },
  { id: 5, word: 'advocate', pos: '動詞', meaning: '主張する、支持する / 名詞：支持者' },
  { id: 6, word: 'affiliate', pos: '名詞', meaning: '系列会社、提携組織 / 動詞：提携する' },
  { id: 7, word: 'alleviate', pos: '動詞', meaning: '（苦痛や問題を）軽減する、緩和する' },
  { id: 8, word: 'amendment', pos: '名詞', meaning: '（契約書などの）修正、改正（案）' },
  { id: 9, word: 'anticipate', pos: '動詞', meaning: '予期する、期待する' },
  { id: 10, word: 'appraise', pos: '動詞', meaning: '評価する、査定する' },
  { id: 11, word: 'articulate', pos: '動詞', meaning: '（考えなどを）明確に述べる / 形容詞：はっきりした' },
  { id: 12, word: 'aspire', pos: '動詞', meaning: '熱望する、志す' },
  { id: 13, word: 'stringent', pos: '形容詞', meaning: '（規則などが）厳格な、厳しい' },
  { id: 14, word: 'attrition', pos: '名詞', meaning: '（人員の）自然減、摩耗' },
  { id: 15, word: 'subsequent', pos: '形容詞', meaning: '次の、その後の' },
  { id: 16, word: 'benchmark', pos: '名詞', meaning: '基準、指標 / 動詞：基準を評価する' },
  { id: 17, word: 'beneficiary', pos: '名詞', meaning: '受益者、（保険金などの）受取人' },
  { id: 18, word: 'breach', pos: '名詞', meaning: '（法律・契約の）違反、不履行 / 動詞：違反する' },
  { id: 19, word: 'lucrative', pos: '形容詞', meaning: '利益の上がる、儲かる' },
  { id: 20, word: 'chronicle', pos: '動詞', meaning: '年代記に記録する / 名詞：年代記、記録' },
  { id: 21, word: 'unprecedented', pos: '形容詞', meaning: '前例のない、未曽有の' },
  { id: 22, word: 'coalition', pos: '名詞', meaning: '（政党などの）連合、提携' },
  { id: 23, word: 'commensurate', pos: '形容詞', meaning: '（数量・程度が）見合った、相応の' },
  { id: 24, word: 'compelling', pos: '形容詞', meaning: '説得力のある、人を引きつける' },
  { id: 25, word: 'concede', pos: '動詞', meaning: '（事実・敗北を）認める、譲歩する' },
  { id: 26, word: 'condone', pos: '動詞', meaning: '（罪などを）容認する、大目に見る' },
  { id: 27, word: 'conducive', pos: '形容詞', meaning: '（環境などが〜に）貢献する、良い影響をもたらす' },
  { id: 28, word: 'congestion', pos: '名詞', meaning: '（交通などの）混雑、渋滞' },
  { id: 29, word: 'conglomerate', pos: '名詞', meaning: '複合企業、コングロマリット' },
  { id: 30, word: 'curtail', pos: '動詞', meaning: '削減する、短縮する' },
  { id: 31, word: 'deficit', pos: '名詞', meaning: '赤字、不足（額）' },
  { id: 32, word: 'delegation', pos: '名詞', meaning: '代表団、（権限の）委任' },
  { id: 33, word: 'demolish', pos: '動詞', meaning: '（建物を）解体する、取り壊す' },
  { id: 34, word: 'depreciate', pos: '動詞', meaning: '価値が下がる、減価償却する' },
  { id: 35, word: 'discrepancy', pos: '名詞', meaning: '（計算や証言の）矛盾、不一致' },
  { id: 36, word: 'disrupt', pos: '動詞', meaning: '混乱させる、中断させる' },
  { id: 37, word: 'disseminate', pos: '動詞', meaning: '（情報・知識を）普及させる、ばらまく' },
  { id: 38, word: 'diversify', pos: '動詞', meaning: '多様化する、投資を分散する' },
  { id: 39, word: 'dividend', pos: '名詞', meaning: '（株の）配当金' },
  { id: 40, word: 'drastic', pos: '形容詞', meaning: '徹底的な、思い切った、急激な' },
  { id: 41, word: 'dwindle', pos: '動詞', meaning: 'だんだん減少する、縮小する' },
  { id: 42, word: 'elevate', pos: '動詞', meaning: '高める、昇進させる' },
  { id: 43, word: 'embark', pos: '動詞', meaning: '（新しい事業などに）乗り出す、着手する' },
  { id: 44, word: 'eminent', pos: '形容詞', meaning: '著名な、卓越した' },
  { id: 45, word: 'endorse', pos: '動詞', meaning: '（有名人が商品を）推薦する、承認する、裏書する' },
  { id: 46, word: 'enforce', pos: '動詞', meaning: '（法律などを）執行する、強制する' },
  { id: 47, word: 'entail', pos: '動詞', meaning: '（結果として）伴う、必要とする' },
  { id: 48, word: 'expedite', pos: '動詞', meaning: '（手続きなどを）迅速に処理する、はかどらせる' },
  { id: 49, word: 'fluctuate', pos: '動詞', meaning: '（価格・数値が）変動する、上下する' },
  { id: 50, word: 'forfeit', pos: '動詞', meaning: '（権利・財産を）没収される、失う' },
  { id: 51, word: 'foster', pos: '動詞', meaning: '促進する、育成する' },
  { id: 52, word: 'imminent', pos: '形容詞', meaning: '（危険などが）差し迫った、目前に迫った' },
  { id: 53, word: 'incentive', pos: '名詞', meaning: '励み、インセンティブ、動機' },
  { id: 54, word: 'incorporate', pos: '動詞', meaning: '組み込む、法人化する' },
  { id: 55, word: 'incur', pos: '動詞', meaning: '（負債・損害・罰を）被る、負う' },
  { id: 56, word: 'indispensable', pos: '形容詞', meaning: '必要不可欠な' },
  { id: 57, word: 'infrastructure', pos: '名詞', meaning: 'インフラ、社会的基盤施設' },
  { id: 58, word: 'infringe', pos: '動詞', meaning: '（権利などを）侵害する、違反する' },
  { id: 59, word: 'interim', pos: '形容詞', meaning: '中間の、暫定の / 名詞：合間' },
  { id: 60, word: 'jeopardize', pos: '動詞', meaning: '危険にさらす、台無しにする' },
  { id: 61, word: 'liability', pos: '名詞', meaning: '法的責任、負債、お荷物' },
  { id: 62, word: 'liquidation', pos: '名詞', meaning: '（会社の）清算、倒産、解散' },
  { id: 63, word: 'mandatory', pos: '形容詞', meaning: '義務的な、強制的な' },
  { id: 64, word: 'merger', pos: '名詞', meaning: '（企業の）合併' },
  { id: 65, word: 'monopoly', pos: '名詞', meaning: '独占、専売' },
  { id: 66, word: 'negligible', pos: '形容詞', meaning: '無視できるほどの、わずかな' },
  { id: 67, word: 'nominate', pos: '動詞', meaning: '推薦する、指名する' },
  { id: 68, word: 'obstacle', pos: '名詞', meaning: '障害（物）、邪魔' },
  { id: 69, word: 'offset', pos: '動詞', meaning: '相殺する、埋め合わせる' },
  { id: 70, word: 'opt', pos: '動詞', meaning: '選択する、決める' },
  { id: 71, word: 'outsource', pos: '動詞', meaning: '外部委託する、アウトソーシングする' },
  { id: 72, word: 'oversee', pos: '動詞', meaning: '監督する、統括する' },
  { id: 73, word: 'patent', pos: '名詞', meaning: '特許（権） / 動詞：特許を取得する' },
  { id: 74, word: 'pinnacle', pos: '名詞', meaning: '頂点、最高峰' },
  { id: 75, word: 'plummet', pos: '動詞', meaning: '（価格・数値が）急落する、垂直に落ちる' },
  { id: 76, word: 'predecessor', pos: '名詞', meaning: '前任者、前身' },
  { id: 77, word: 'prohibit', pos: '動詞', meaning: '禁止する' },
  { id: 78, word: 'prospective', pos: '形容詞', meaning: '見込みのある、将来の' },
  { id: 79, word: 'provisional', pos: '形容詞', meaning: '暫定的な、仮の' },
  { id: 80, word: 'prudent', pos: '形容詞', meaning: '慎重な、分別のある' },
  { id: 81, word: 'rebate', pos: '名詞', meaning: '払い戻し、キックバック' },
  { id: 82, word: 'recipient', pos: '名詞', meaning: '受け取り手、受賞者' },
  { id: 83, word: 'rectify', pos: '動詞', meaning: '修正する、是正する' },
  { id: 84, word: 'redundant', pos: '形容詞', meaning: '余剰の、人員削減された、重複する' },
  { id: 85, word: 'relinquish', pos: '動詞', meaning: '（権利・地位を）放棄する、譲渡する' },
  { id: 86, word: 'remembrance', pos: '名詞', meaning: '形見、記憶、思い出' },
  { id: 87, word: 'renowned', pos: '形容詞', meaning: '有名な、名高い' },
  { id: 88, word: 'requisite', pos: '形容詞', meaning: '必要な、必須の / 名詞：必要条件' },
  { id: 89, word: 'solicit', pos: '動詞', meaning: '（注文・意見などを）懇請する、強く求める' },
  { id: 90, word: 'speculate', pos: '動詞', meaning: '推測する、投機する' },
  { id: 91, word: 'stagnant', pos: '形容詞', meaning: '（経済・水などが）停滞した、不活発な' },
  { id: 92, word: 'stipulate', pos: '動詞', meaning: '（契約で）規定する、明文化する' },
  { id: 93, word: 'surplus', pos: '名詞', meaning: '黒字、剰余（額） / 形容詞：余剰の' },
  { id: 94, word: 'sustainable', pos: '形容詞', meaning: '持続可能な' },
  { id: 95, word: 'tedious', pos: '形容詞', meaning: '（仕事などが）退屈な、長くてうんざりする' },
  { id: 96, word: 'terminate', pos: '動詞', meaning: '（契約などを）終了させる、解雇する' },
  { id: 97, word: 'thrive', pos: '動詞', meaning: '繁栄する、繁盛する' },
  { id: 98, word: 'unanimous', pos: '形容詞', meaning: '満場一致の、全員賛成の' },
  { id: 99, word: 'vendor', pos: '名詞', meaning: '業者、売り手' },
  { id: 100, word: 'volatile', pos: '形容詞', meaning: '（価格などが）変動しやすい、不安定な' }
];

export default WORDS;